import useTranslation from '../intl/useTranslation';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  const [translate, language, updateLang] = useTranslation();

  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className='text-red-900'>{translate('about')}</h1>
        <button onClick={() => updateLang('id')}>ID</button>
        <button onClick={() => updateLang('en')}>EN</button>
      </main>
    </div>
  );
};

export default Home;
